# .github/workflows/deploy-production.yml
name: Deploy to konspiredesign.com
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      DEPLOY_TO: 'apprunner@konspiredesign.com:/var/www/konspiredesign.com'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
      
      - name: Deploy
        run: |
          rsync -avz --delete \
            --exclude={'.git','.github','node_modules','.env','*.log'} \
            ./ ${{ env.DEPLOY_TO }}/tmp/
          ssh ${DEPLOY_TO%:*} "\
            cd ${DEPLOY_TO#*:}/tmp && \
            npm ci --production && \
            touch ../current/tmp/restart.txt && \
            cd .. && \
            rm -rf current && \
            mv tmp current"
            
      - name: Verify
        run: curl --fail -I https://konspiredesign.com || exit 1